-- ============================================================================
-- Aidly ERP Inventory (INV) module PostgreSQL script
-- Generated from the current backend JPA mappings, then extended with
-- production-grade live-row uniqueness, lookup indexes, menu seed, and optional
-- document sequence seed.
--
-- Run order:
--   1. Run the SYS/common base schema first.
--   2. Run this file.
--   3. Configure FIN_1006 GL mappings for:
--      OpeningStockPosted / INVENTORY
--      OpeningStockPosted / OPENING_EQUITY
--      StockAdjustmentPosted / INVENTORY
--      StockAdjustmentPosted / ADJUSTMENT
--      StockAdjustmentReversed / INVENTORY
--      StockAdjustmentReversed / ADJUSTMENT
-- ============================================================================

BEGIN;

-- ---- INV tables -------------------------------------------------------------

CREATE TABLE IF NOT EXISTS inv_batch (expiry_date date, is_active smallint not null, is_deleted smallint not null, mfg_date date, mrp numeric(20,4), received_cost numeric(20,6) not null, batch_no bigint generated by default as identity, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, product_no bigint not null, row_version bigint not null, supplier_no bigint, updated_at timestamp(6), updated_by bigint, variant_no bigint, batch_code varchar(60) not null, remarks text, primary key (batch_no));
CREATE TABLE IF NOT EXISTS inv_brand (is_active smallint not null, is_deleted smallint not null, brand_no bigint generated by default as identity, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, row_version bigint not null, updated_at timestamp(6), updated_by bigint, brand_id varchar(30) not null, brand_name varchar(150) not null, brand_name_nls varchar(150), manufacturer varchar(200), image_path varchar(255), remarks text, primary key (brand_no));
CREATE TABLE IF NOT EXISTS inv_category (depth smallint not null, is_active smallint not null, is_deleted smallint not null, order_sl integer not null, branch_no bigint, category_no bigint generated by default as identity, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, default_vat_tax_no bigint, deleted_at timestamp(6), deleted_by bigint, parent_category_no bigint, row_version bigint not null, updated_at timestamp(6), updated_by bigint, category_id varchar(30) not null, category_name varchar(150) not null, category_name_nls varchar(150), tree_path varchar(500), image_path varchar(255), remarks text, primary key (category_no));
CREATE TABLE IF NOT EXISTS inv_product (allow_discount smallint not null, cost_price numeric(20,6) not null, default_margin_pct numeric(5,2), has_variants smallint not null, is_active smallint not null, is_batch_tracked smallint not null, is_deleted smallint not null, is_expiry_tracked smallint not null, is_purchasable smallint not null, is_sellable smallint not null, is_serial_tracked smallint not null, is_stock_tracked smallint not null, is_tax_inclusive smallint not null, max_stock numeric(18,4), min_sale_price numeric(20,4), min_stock numeric(18,4) not null, mrp numeric(20,4) not null, product_type smallint not null, purchase_price numeric(20,6) not null, reorder_level numeric(18,4) not null, reorder_qty numeric(18,4) not null, sale_price numeric(20,4) not null, shelf_life_days integer, weight_gm numeric(18,4), base_uom_no bigint not null, brand_no bigint, category_no bigint not null, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, product_no bigint generated by default as identity, purchase_uom_no bigint, row_version bigint not null, sales_uom_no bigint, updated_at timestamp(6), updated_by bigint, vat_tax_no bigint, hsn_sac_code varchar(20), product_id varchar(40) not null, short_name varchar(60), barcode varchar(64), product_name varchar(200) not null, product_name_nls varchar(200), image_path varchar(255), remarks text, primary key (product_no));
CREATE TABLE IF NOT EXISTS inv_product_attribute (is_active smallint not null, is_deleted smallint not null, order_sl integer not null, attribute_no bigint generated by default as identity, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, row_version bigint not null, updated_at timestamp(6), updated_by bigint, attribute_id varchar(30) not null, attribute_name varchar(60) not null, primary key (attribute_no));
CREATE TABLE IF NOT EXISTS inv_product_attribute_value (is_active smallint not null, is_deleted smallint not null, order_sl integer not null, attribute_no bigint not null, attribute_value_no bigint generated by default as identity, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, row_version bigint not null, updated_at timestamp(6), updated_by bigint, value_code varchar(30) not null, value_name varchar(60) not null, primary key (attribute_value_no));
CREATE TABLE IF NOT EXISTS inv_product_barcode (barcode_type smallint not null, is_active smallint not null, is_deleted smallint not null, is_primary smallint not null, pack_qty numeric(18,4) not null, barcode_no bigint generated by default as identity, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, product_no bigint not null, row_version bigint not null, uom_no bigint not null, updated_at timestamp(6), updated_by bigint, variant_no bigint, barcode varchar(64) not null, primary key (barcode_no));
CREATE TABLE IF NOT EXISTS inv_product_variant (is_active smallint not null, is_deleted smallint not null, mrp numeric(20,4), purchase_price numeric(20,6), sale_price numeric(20,4), attr1_value_no bigint, attr2_value_no bigint, attr3_value_no bigint, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, product_no bigint not null, row_version bigint not null, updated_at timestamp(6), updated_by bigint, variant_no bigint generated by default as identity, variant_sku varchar(48) not null, barcode varchar(64), variant_name varchar(200) not null, image_path varchar(255), primary key (variant_no));
CREATE TABLE IF NOT EXISTS inv_rack (is_active smallint not null, is_deleted smallint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, rack_no bigint generated by default as identity, row_version bigint not null, updated_at timestamp(6), updated_by bigint, warehouse_no bigint not null, aisle varchar(20), bin varchar(20), rack varchar(20), shelf varchar(20), rack_id varchar(30) not null, rack_name varchar(100), primary key (rack_no));
CREATE TABLE IF NOT EXISTS inv_reorder (is_active smallint not null, is_deleted smallint not null, lead_time_days integer, max_stock numeric(18,4), min_stock numeric(18,4) not null, reorder_level numeric(18,4) not null, reorder_qty numeric(18,4) not null, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, preferred_supplier_no bigint, product_no bigint not null, reorder_no bigint generated by default as identity, row_version bigint not null, updated_at timestamp(6), updated_by bigint, variant_no bigint, warehouse_no bigint not null, primary key (reorder_no));
CREATE TABLE IF NOT EXISTS inv_stock (avg_cost numeric(20,6) not null, last_cost numeric(20,6) not null, qty_available numeric(18,4), qty_on_hand numeric(18,4) not null, qty_reserved numeric(18,4) not null, stock_value numeric(20,4), batch_no bigint, branch_no bigint not null, company_no bigint not null, created_at timestamp(6) not null, last_movement_at timestamp(6), product_no bigint not null, row_version bigint not null, stock_no bigint generated by default as identity, updated_at timestamp(6), variant_no bigint, warehouse_no bigint not null, primary key (stock_no));
CREATE TABLE IF NOT EXISTS inv_stock_adjustment (adjustment_date date not null, adjustment_type smallint not null, is_active smallint not null, is_deleted smallint not null, reason_code smallint, status smallint not null, total_in_value numeric(20,4) not null, total_out_value numeric(20,4) not null, adjustment_no bigint generated by default as identity, approved_at timestamp(6), approved_by bigint, branch_no bigint not null, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, fin_period_no bigint, fin_year_no bigint not null, gl_voucher_no bigint, posted_at timestamp(6), row_version bigint not null, submitted_at timestamp(6), submitted_by bigint, updated_at timestamp(6), updated_by bigint, warehouse_no bigint not null, adjustment_id varchar(40) not null, reason_text varchar(250), remarks text, primary key (adjustment_no));
CREATE TABLE IF NOT EXISTS inv_stock_adjustment_dtl (direction smallint not null, line_no integer not null, line_value numeric(20,4) not null, qty numeric(18,4) not null, qty_base numeric(18,4) not null, system_qty numeric(18,4), unit_cost numeric(20,6) not null, adjustment_dtl_no bigint generated by default as identity, adjustment_no bigint not null, batch_no bigint, product_no bigint not null, rack_no bigint, row_version bigint not null, uom_no bigint not null, variant_no bigint, remarks varchar(250), primary key (adjustment_dtl_no));
CREATE TABLE IF NOT EXISTS inv_stock_ledger (avg_cost_after numeric(20,6) not null, balance_after numeric(18,4) not null, direction smallint not null, is_reversal smallint not null, movement_date date not null, movement_type smallint not null, qty_base numeric(18,4) not null, ref_doc_type smallint not null, total_cost numeric(20,4) not null, unit_cost numeric(20,6) not null, batch_no bigint, branch_no bigint not null, company_no bigint not null, created_at timestamp(6) not null, created_by bigint not null, fin_period_no bigint, fin_year_no bigint not null, product_no bigint not null, ref_doc_pk bigint, ref_line_no bigint, reversed_ledger_no bigint, stock_ledger_no bigint generated by default as identity, variant_no bigint, warehouse_no bigint not null, ref_doc_no varchar(40) not null, remarks varchar(250), primary key (stock_ledger_no));
CREATE TABLE IF NOT EXISTS inv_stock_transfer (is_active smallint not null, is_deleted smallint not null, status smallint not null, total_qty numeric(18,4) not null, total_value numeric(20,4) not null, transfer_date date not null, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, dispatched_at timestamp(6), dispatched_by bigint, from_branch_no bigint not null, from_warehouse_no bigint not null, received_at timestamp(6), received_by bigint, row_version bigint not null, to_branch_no bigint not null, to_warehouse_no bigint not null, transfer_no bigint generated by default as identity, transit_warehouse_no bigint, updated_at timestamp(6), updated_by bigint, transfer_id varchar(40) not null, remarks text, primary key (transfer_no));
CREATE TABLE IF NOT EXISTS inv_stock_transfer_dtl (line_no integer not null, line_value numeric(20,4) not null, qty_received numeric(18,4), qty_received_base numeric(18,4), qty_sent numeric(18,4) not null, qty_sent_base numeric(18,4) not null, unit_cost numeric(20,6) not null, batch_no bigint, product_no bigint not null, row_version bigint not null, transfer_dtl_no bigint generated by default as identity, transfer_no bigint not null, uom_no bigint not null, variant_no bigint, remarks varchar(250), primary key (transfer_dtl_no));
CREATE TABLE IF NOT EXISTS inv_uom (decimal_places smallint not null, is_active smallint not null, is_deleted smallint not null, uom_type smallint not null, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, row_version bigint not null, uom_no bigint generated by default as identity, updated_at timestamp(6), updated_by bigint, uom_id varchar(20) not null, uom_name varchar(50) not null, uom_name_nls varchar(50), remarks text, primary key (uom_no));
CREATE TABLE IF NOT EXISTS inv_uom_conversion (is_active smallint not null, is_deleted smallint not null, to_base_factor numeric(18,6) not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, from_uom_no bigint not null, product_no bigint not null, row_version bigint not null, uom_conversion_no bigint generated by default as identity, updated_at timestamp(6), updated_by bigint, primary key (uom_conversion_no));
CREATE TABLE IF NOT EXISTS inv_valuation_layer (is_exhausted smallint not null, original_qty numeric(18,4) not null, receipt_date date not null, remaining_qty numeric(18,4) not null, unit_cost numeric(20,6) not null, batch_no bigint, company_no bigint not null, created_at timestamp(6) not null, layer_no bigint generated by default as identity, product_no bigint not null, receipt_ledger_no bigint not null, row_version bigint not null, updated_at timestamp(6), variant_no bigint, warehouse_no bigint not null, primary key (layer_no));
CREATE TABLE IF NOT EXISTS inv_warehouse (allow_negative_stock smallint not null, is_active smallint not null, is_default smallint not null, is_deleted smallint not null, is_sale_point smallint not null, warehouse_type smallint not null, branch_no bigint not null, company_no bigint not null, created_at timestamp(6) not null, created_by bigint, deleted_at timestamp(6), deleted_by bigint, manager_employee_no bigint, row_version bigint not null, updated_at timestamp(6), updated_by bigint, warehouse_no bigint generated by default as identity, warehouse_id varchar(30) not null, warehouse_name varchar(150) not null, warehouse_name_nls varchar(150), address varchar(250), remarks text, primary key (warehouse_no));

-- ---- Generated indexes -----------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_inv_batch_expiry ON inv_batch (expiry_date);
CREATE INDEX IF NOT EXISTS idx_inv_batch_product ON inv_batch (product_no, variant_no);
CREATE INDEX IF NOT EXISTS idx_inv_brand_company_deleted ON inv_brand (company_no, is_deleted);
CREATE INDEX IF NOT EXISTS idx_inv_category_parent ON inv_category (parent_category_no);
CREATE INDEX IF NOT EXISTS idx_inv_category_active ON inv_category (company_no, is_active);
CREATE INDEX IF NOT EXISTS idx_inv_product_category ON inv_product (category_no);
CREATE INDEX IF NOT EXISTS idx_inv_product_brand ON inv_product (brand_no);
CREATE INDEX IF NOT EXISTS idx_inv_product_active ON inv_product (company_no, is_active);
CREATE INDEX IF NOT EXISTS idx_inv_attr_company_deleted ON inv_product_attribute (company_no, is_deleted);
CREATE INDEX IF NOT EXISTS idx_inv_attrval_attr ON inv_product_attribute_value (attribute_no);
CREATE INDEX IF NOT EXISTS idx_inv_barcode_product ON inv_product_barcode (product_no, variant_no);
CREATE INDEX IF NOT EXISTS idx_inv_variant_product ON inv_product_variant (product_no);
CREATE INDEX IF NOT EXISTS idx_inv_rack_warehouse_deleted ON inv_rack (warehouse_no, is_deleted);
CREATE INDEX IF NOT EXISTS idx_inv_reorder_wh ON inv_reorder (warehouse_no, is_deleted);
CREATE INDEX IF NOT EXISTS idx_inv_stock_product ON inv_stock (product_no, variant_no);
CREATE INDEX IF NOT EXISTS idx_inv_stock_branch ON inv_stock (branch_no, warehouse_no);
CREATE INDEX IF NOT EXISTS idx_inv_adj_status ON inv_stock_adjustment (branch_no, status, is_deleted);
CREATE INDEX IF NOT EXISTS idx_inv_adj_wh_date ON inv_stock_adjustment (warehouse_no, adjustment_date);
CREATE INDEX IF NOT EXISTS idx_inv_adjdtl_hdr ON inv_stock_adjustment_dtl (adjustment_no);
CREATE INDEX IF NOT EXISTS idx_inv_ledger_cell ON inv_stock_ledger (warehouse_no, product_no, variant_no, batch_no, stock_ledger_no);
CREATE INDEX IF NOT EXISTS idx_inv_ledger_ref ON inv_stock_ledger (ref_doc_type, ref_doc_no);
CREATE INDEX IF NOT EXISTS idx_inv_ledger_date ON inv_stock_ledger (branch_no, movement_date);
CREATE INDEX IF NOT EXISTS idx_inv_ledger_product_date ON inv_stock_ledger (product_no, movement_date);
CREATE INDEX IF NOT EXISTS idx_inv_xfer_status ON inv_stock_transfer (status, is_deleted);
CREATE INDEX IF NOT EXISTS idx_inv_xfer_from ON inv_stock_transfer (from_warehouse_no, transfer_date);
CREATE INDEX IF NOT EXISTS idx_inv_xferdtl_hdr ON inv_stock_transfer_dtl (transfer_no);
CREATE INDEX IF NOT EXISTS idx_inv_uom_company_deleted ON inv_uom (company_no, is_deleted);
CREATE INDEX IF NOT EXISTS idx_inv_uomconv_product ON inv_uom_conversion (product_no);
CREATE INDEX IF NOT EXISTS idx_inv_layer_fifo ON inv_valuation_layer (warehouse_no, product_no, variant_no, batch_no, receipt_date, layer_no);
CREATE INDEX IF NOT EXISTS idx_inv_wh_branch ON inv_warehouse (branch_no, is_deleted);

-- ---- Production guardrails -------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_brand_id_company_live
    ON inv_brand (company_no, brand_id)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_brand_name_company_live
    ON inv_brand (company_no, brand_name)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_category_id_company_live
    ON inv_category (company_no, category_id)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_category_name_company_live
    ON inv_category (company_no, category_name)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_uom_id_company_live
    ON inv_uom (company_no, uom_id)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_product_id_company_live
    ON inv_product (company_no, product_id)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_product_barcode_company_live
    ON inv_product (company_no, barcode)
    WHERE is_deleted = 0 AND barcode IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_attribute_id_company_live
    ON inv_product_attribute (company_no, attribute_id)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_attribute_value_code_live
    ON inv_product_attribute_value (attribute_no, value_code)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_product_barcode_live
    ON inv_product_barcode (company_no, barcode)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_product_variant_sku_live
    ON inv_product_variant (product_no, variant_sku)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_warehouse_id_branch_live
    ON inv_warehouse (branch_no, warehouse_id)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_warehouse_default_branch_live
    ON inv_warehouse (branch_no)
    WHERE is_deleted = 0 AND is_default = 1;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_rack_id_warehouse_live
    ON inv_rack (warehouse_no, rack_id)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_reorder_cell_live
    ON inv_reorder (warehouse_no, product_no, (COALESCE(variant_no, 0)))
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_stock_cell
    ON inv_stock (warehouse_no, product_no, (COALESCE(variant_no, 0)), (COALESCE(batch_no, 0)));

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_adjustment_id_branch_live
    ON inv_stock_adjustment (branch_no, adjustment_id)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_transfer_id_company_live
    ON inv_stock_transfer (company_no, transfer_id)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_uom_conversion_product_uom_live
    ON inv_uom_conversion (product_no, from_uom_no)
    WHERE is_deleted = 0;

CREATE UNIQUE INDEX IF NOT EXISTS uq_inv_docseq_company_branch_type_year
    ON sys_doc_sequence (company_no, branch_no, doc_type, (COALESCE(fin_year_no, 0)));

CREATE INDEX IF NOT EXISTS idx_inv_product_company_name_live
    ON inv_product (company_no, product_name)
    WHERE is_deleted = 0;

CREATE INDEX IF NOT EXISTS idx_inv_stock_available_lookup
    ON inv_stock (company_no, branch_no, warehouse_no, product_no, (COALESCE(variant_no, 0)), (COALESCE(batch_no, 0)));

CREATE INDEX IF NOT EXISTS idx_inv_batch_company_product_expiry_live
    ON inv_batch (company_no, product_no, (COALESCE(variant_no, 0)), expiry_date)
    WHERE is_deleted = 0 AND is_active = 1;

-- ---- Menu seed -------------------------------------------------------------

INSERT INTO sys_module (module_code, module_name, module_route, module_icon, order_sl, is_active, is_deleted, row_version, created_at)
SELECT 'INV', 'Inventory', 'inv', 'inventory_2', 30, 1, 0, 1, now()
WHERE NOT EXISTS (SELECT 1 FROM sys_module WHERE module_code = 'INV' AND is_deleted = 0);

INSERT INTO sys_submodule (module_no, submodule_code, submodule_name, submodule_icon, order_sl, is_active, is_deleted, row_version, created_at)
SELECT m.module_no, 'INV-PROD', 'Product Management', 'inventory_2', 1, 1, 0, 1, now()
FROM sys_module m
WHERE m.module_code = 'INV'
  AND NOT EXISTS (SELECT 1 FROM sys_submodule s WHERE s.module_no = m.module_no AND s.submodule_code = 'INV-PROD');

INSERT INTO sys_submodule (module_no, submodule_code, submodule_name, submodule_icon, order_sl, is_active, is_deleted, row_version, created_at)
SELECT m.module_no, 'INV-STOCK', 'Stock Operations', 'inventory', 2, 1, 0, 1, now()
FROM sys_module m
WHERE m.module_code = 'INV'
  AND NOT EXISTS (SELECT 1 FROM sys_submodule s WHERE s.module_no = m.module_no AND s.submodule_code = 'INV-STOCK');

INSERT INTO sys_submodule (module_no, submodule_code, submodule_name, submodule_icon, order_sl, is_active, is_deleted, row_version, created_at)
SELECT m.module_no, 'INV-WH', 'Warehouse & Transfer', 'warehouse', 3, 1, 0, 1, now()
FROM sys_module m
WHERE m.module_code = 'INV'
  AND NOT EXISTS (SELECT 1 FROM sys_submodule s WHERE s.module_no = m.module_no AND s.submodule_code = 'INV-WH');

WITH menu_seed(submodule_code, form_id, form_name, route_path, icon_name, order_sl) AS (
    VALUES
        ('INV-PROD',  'INV_1001', 'Product Master',          '/inv/form/product-master-setup',    'inventory_2', 1),
        ('INV-PROD',  'INV_1002', 'Barcode Generator',       '/inv/form/barcode-generator',       'qr_code', 2),
        ('INV-PROD',  'INV_1003', 'Category Setup',          '/inv/form/category-setup',          'category', 3),
        ('INV-PROD',  'INV_1004', 'Brand Setup',             '/inv/form/brand-setup',             'sell', 4),
        ('INV-PROD',  'INV_1005', 'Unit of Measure Setup',   '/inv/form/unit-of-measure-setup',   'straighten', 5),
        ('INV-PROD',  'INV_1006', 'Product Attribute Setup', '/inv/form/product-attribute-setup', 'tune', 6),
        ('INV-STOCK', 'INV_1101', 'Opening Stock',           '/inv/form/opening-stock-entry',     'inventory', 1),
        ('INV-STOCK', 'INV_1102', 'Stock Adjustment',        '/inv/form/stock-adjustment',        'edit_note', 2),
        ('INV-WH',    'INV_2001', 'Warehouse Setup',         '/inv/form/warehouse-setup',         'warehouse', 1),
        ('INV-WH',    'INV_2002', 'Rack/Shelf Setup',        '/inv/form/rack-shelf-setup',        'shelves', 2),
        ('INV-WH',    'INV_2003', 'Stock Transfer',          '/inv/form/stock-transfer',          'local_shipping', 3),
        ('INV-WH',    'INV_2004', 'Batch / Expiry Management','/inv/form/batch-expiry-management','event_busy', 4),
        ('INV-WH',    'INV_2005', 'Reorder Level Setup',     '/inv/form/reorder-level-setup',     'production_quantity_limits', 5)
)
INSERT INTO sys_menu (submodule_no, form_id, form_name, menu_type, route_path, icon_name, order_sl, is_active, is_deleted, row_version, created_at)
SELECT s.submodule_no, ms.form_id, ms.form_name, 'form', ms.route_path, ms.icon_name, ms.order_sl, 1, 0, 1, now()
FROM menu_seed ms
JOIN sys_submodule s ON s.submodule_code = ms.submodule_code
JOIN sys_module m ON m.module_no = s.module_no AND m.module_code = 'INV'
WHERE NOT EXISTS (SELECT 1 FROM sys_menu mn WHERE mn.form_id = ms.form_id AND mn.is_deleted = 0);

-- Company-wide enrollment for every existing company. Keep branch_no NULL so
-- branch-specific RBAC can still be managed by roles while licensing is enabled.
INSERT INTO sys_enroll_menu (company_no, branch_no, menu_no, is_lifetime, is_active, is_deleted, row_version, created_at, created_by)
SELECT c.company_no, NULL, mn.menu_no, 1, 1, 0, 1, now(), (SELECT min(user_no) FROM sys_user WHERE is_deleted = 0)
FROM sys_company c
JOIN sys_menu mn ON mn.form_id LIKE 'INV/_%' ESCAPE '/' AND mn.is_deleted = 0
WHERE c.is_deleted = 0
  AND NOT EXISTS (
      SELECT 1
      FROM sys_enroll_menu e
      WHERE e.company_no = c.company_no
        AND e.menu_no = mn.menu_no
        AND e.branch_no IS NULL
        AND e.is_deleted = 0
  );

-- Optional sequence seeds. The application can auto-create these rows, but
-- seeding gives predictable prefixes for existing financial years and branches.
WITH seq_seed(doc_type, prefix) AS (
    VALUES ('INV_ADJ', 'ADJ-'), ('INV_XFER', 'XFER-')
)
INSERT INTO sys_doc_sequence (company_no, branch_no, doc_type, fin_year_no, prefix, suffix, next_no, padding, reset_policy, row_version)
SELECT b.company_no, b.branch_no, ss.doc_type, fy.fin_year_no, ss.prefix, '', 1, 6, 2, 1
FROM sys_branch b
JOIN sys_fin_year fy ON fy.company_no = b.company_no AND fy.is_deleted = 0
CROSS JOIN seq_seed ss
WHERE b.is_deleted = 0
  AND (fy.branch_no IS NULL OR fy.branch_no = b.branch_no)
  AND NOT EXISTS (
      SELECT 1
      FROM sys_doc_sequence d
      WHERE d.company_no = b.company_no
        AND d.branch_no = b.branch_no
        AND d.doc_type = ss.doc_type
        AND d.fin_year_no = fy.fin_year_no
  );

COMMIT;
